name: "Update Wiki"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout the main repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout the wiki repository
      uses: actions/checkout@v2
      with:
        repository: "${{ github.repository }}.wiki"
        ref: master
        path: .wiki

    - name: Generate the Wiki Page
      run: |
        set -xe
        ./generate-wikipage | tee .wiki/Home.md

    - name: Configure the GitHub wiki identity
      working-directory: .wiki
      run: |
        set -xe
        git config user.name  "[bot] ${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}+bot@users.noreply.github.com"

    - name: Update the wiki page
      working-directory: .wiki
      run: |
        set -xe
        git add .
        git commit -m "update the wiki page by bot (${GITHUB_WORKFLOW})"
        git push origin master
